
server:
  port: 8051
  host: localhost

spring:
  application:
    name: praxis-microservices-qrcode

logging:
  level:
    root: INFO
    org.springframework.web.client: INFO
    org.springframework.security.oauth2: INFO
    com.praxis.qrcode.infrastructure.client: DEBUG
    com.praxis.qrcode.config.jwt: TRACE



#INFORMATION
info:
  app:
    description: Projeto PRAXIS PIX QRCode
    name: ${spring.application.name}
    version: 1.0.0